name: BasicPlugin
version: 1.0
main: com.yourname.basicplugin.Main
api-version: 1.16
commands:
  dc:
    description: Provides the Discord link.
    usage: /<command>
  discord:
    description: Provides the Discord link.
    usage: /<command>
  store:
    description: Provides the store link.
    usage: /<command>
  s:
    description: Provides the store link.
    usage: /<command>
